- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - navigation [ref=e3]:
      - generic [ref=e4]:
        - generic [ref=e5]:
          - 'link " ROS 2 Documentation: Rolling Logo" [ref=e6] [cursor=pointer]':
            - /url: ../../../index.html
            - text: " ROS 2 Documentation: Rolling"
            - img "Logo" [ref=e7]
          - search [ref=e8]:
            - textbox "Search docs" [ref=e10]
        - navigation "Navigation menu" [ref=e11]:
          - list [ref=e12]:
            - listitem [ref=e13]:
              - link "About ROS" [ref=e14] [cursor=pointer]:
                - /url: ../../../About-ROS.html
            - listitem [ref=e15]:
              - link " Installation" [ref=e16] [cursor=pointer]:
                - /url: ../../../Installation.html
                - button "" [ref=e17]
                - text: Installation
              - text:    
            - listitem [ref=e18]:
              - link " Distributions" [ref=e19] [cursor=pointer]:
                - /url: ../../../Releases.html
                - button "" [ref=e20]
                - text: Distributions
              - text:         
            - listitem [ref=e21]:
              - link " Tutorials" [ref=e22] [cursor=pointer]:
                - /url: ../../../Tutorials.html
                - button "" [ref=e23]
                - text: Tutorials
              - list [ref=e24]:
                - listitem [ref=e25]:
                  - link "First steps with ROS - learning path" [ref=e26] [cursor=pointer]:
                    - /url: ../../../First-Steps.html
                - listitem [ref=e27]:
                  - 'link " Beginner: CLI tools" [ref=e28] [cursor=pointer]':
                    - /url: ../../Beginner-CLI-Tools.html
                    - button "" [ref=e29]
                    - text: "Beginner: CLI tools"
                - listitem [ref=e30]:
                  - 'link " Beginner: Client libraries" [ref=e31] [cursor=pointer]':
                    - /url: ../../Beginner-Client-Libraries.html
                    - button "" [ref=e32]
                    - text: "Beginner: Client libraries"
                - listitem [ref=e33]:
                  - link " Intermediate" [ref=e34] [cursor=pointer]:
                    - /url: ../../Intermediate.html
                    - button "" [ref=e35]
                    - text: Intermediate
                  - text:     
                - listitem [ref=e36]:
                  - link " Advanced" [ref=e37] [cursor=pointer]:
                    - /url: ../../Advanced.html
                    - button "" [ref=e38]
                    - text: Advanced
                  - list [ref=e39]:
                    - listitem [ref=e40]:
                      - link "Supplementing custom rosdep keys" [ref=e41] [cursor=pointer]:
                        - /url: ../Supplementing-Custom-Rosdep-Keys.html
                    - listitem [ref=e42]:
                      - link "Enabling topic statistics (C++)" [ref=e43] [cursor=pointer]:
                        - /url: ../Topic-Statistics-Tutorial/Topic-Statistics-Tutorial.html
                    - listitem [ref=e44]:
                      - link "Topic Keys Tutorial" [ref=e45] [cursor=pointer]:
                        - /url: ../Topic-Keys/Topic-Keys-Tutorial.html
                    - listitem [ref=e46]:
                      - link "Topic Keys Subscription Filtering Tutorial" [ref=e47] [cursor=pointer]:
                        - /url: ../Topic-Keys/Filtered-Topic-Keys-Tutorial.html
                    - listitem [ref=e48]:
                      - link "Using Fast DDS Discovery Server as discovery protocol [community-contributed]" [ref=e49] [cursor=pointer]:
                        - /url: ../Discovery-Server/Discovery-Server.html
                    - listitem [ref=e50]:
                      - link "Implementing a custom memory allocator" [ref=e51] [cursor=pointer]:
                        - /url: ../Allocator-Template-Tutorial.html
                    - listitem [ref=e52]:
                      - link "Ament Lint CLI Utilities" [ref=e53] [cursor=pointer]:
                        - /url: ../Ament-Lint-For-Clean-Code.html
                    - listitem [ref=e54]:
                      - link "Unlocking the potential of Fast DDS middleware [community-contributed]" [ref=e55] [cursor=pointer]:
                        - /url: ../FastDDS-Configuration.html
                    - listitem [ref=e56]:
                      - link "Improved Dynamic Discovery" [ref=e57] [cursor=pointer]:
                        - /url: ../Improved-Dynamic-Discovery.html
                    - listitem [ref=e58]:
                      - link "Recording a bag from a node (C++)" [ref=e59] [cursor=pointer]:
                        - /url: ../Recording-A-Bag-From-Your-Own-Node-CPP.html
                    - listitem [ref=e60]:
                      - link "Recording a bag from a node (Python)" [ref=e61] [cursor=pointer]:
                        - /url: ../Recording-A-Bag-From-Your-Own-Node-Py.html
                    - listitem [ref=e62]:
                      - link "Reading from a bag file (C++)" [ref=e63] [cursor=pointer]:
                        - /url: ../Reading-From-A-Bag-File-CPP.html
                    - listitem [ref=e64]:
                      - link "Reading from a bag file (Python)" [ref=e65] [cursor=pointer]:
                        - /url: ../Reading-From-A-Bag-File-Python.html
                    - listitem [ref=e66]:
                      - link "Create an rqt_bag Plugin" [ref=e67] [cursor=pointer]:
                        - /url: ../Create-An-Rqtbag-Plugin.html
                    - listitem [ref=e68]:
                      - link "How to use ros2_tracing to trace and analyze an application" [ref=e69] [cursor=pointer]:
                        - /url: ../ROS2-Tracing-Trace-and-Analyze.html
                    - listitem [ref=e70]:
                      - link "Creating an rmw implementation" [ref=e71] [cursor=pointer]:
                        - /url: ../Creating-An-RMW-Implementation.html
                        - text: Creating an
                        - code [ref=e72]: rmw
                        - text: implementation
                    - listitem [ref=e73]:
                      - link "Writing a rosidl::Buffer backend" [ref=e74] [cursor=pointer]:
                        - /url: ../Writing-a-Buffer-Backend.html
                        - text: Writing a
                        - code [ref=e75]: rosidl::Buffer
                        - text: backend
                    - listitem [ref=e76]:
                      - link "Writing a rosidl::Buffer compatible conversions package" [ref=e77] [cursor=pointer]:
                        - /url: ../Writing-a-Buffer-Compatible-Conversions-Package.html
                        - text: Writing a
                        - code [ref=e78]: rosidl::Buffer
                        - text: compatible conversions package
                    - listitem [ref=e79]:
                      - link " Simulators" [ref=e80] [cursor=pointer]:
                        - /url: ../Simulators/Simulation-Main.html
                        - button "" [ref=e81]
                        - text: Simulators
                      - text:   
                    - listitem [ref=e82]:
                      - link " Security" [ref=e83] [cursor=pointer]:
                        - /url: Security-Main.html
                        - button "" [ref=e84]
                        - text: Security
                      - list [ref=e85]:
                        - listitem [ref=e86]:
                          - link "Setting up security" [ref=e87] [cursor=pointer]:
                            - /url: Introducing-ros2-security.html
                        - listitem [ref=e88]:
                          - link "Understanding the security keystore" [ref=e89] [cursor=pointer]:
                            - /url: The-Keystore.html
                        - listitem [ref=e90]:
                          - link "Ensuring security across machines" [ref=e91] [cursor=pointer]:
                            - /url: Security-on-Two.html
                        - listitem [ref=e92]:
                          - link "Examining network traffic" [ref=e93] [cursor=pointer]:
                            - /url: Examine-Traffic.html
                        - listitem [ref=e94]:
                          - link "Setting access controls" [expanded] [ref=e95] [cursor=pointer]:
                            - /url: "#"
                        - listitem [ref=e96]:
                          - link "Deployment Guidelines" [ref=e97] [cursor=pointer]:
                            - /url: Deployment-Guidelines.html
                - listitem [ref=e98]:
                  - link " Demos" [ref=e99] [cursor=pointer]:
                    - /url: ../../Demos.html
                    - button "" [ref=e100]
                    - text: Demos
                - listitem [ref=e101]:
                  - link " Miscellaneous" [ref=e102] [cursor=pointer]:
                    - /url: ../../Miscellaneous.html
                    - button "" [ref=e103]
                    - text: Miscellaneous
            - listitem [ref=e104]:
              - link " How-to Guides" [ref=e105] [cursor=pointer]:
                - /url: ../../../How-To-Guides.html
                - button "" [ref=e106]
                - text: How-to Guides
              - text:  
            - listitem [ref=e107]:
              - link " Concepts" [ref=e108] [cursor=pointer]:
                - /url: ../../../Concepts.html
                - button "" [ref=e109]
                - text: Concepts
              - text:    
            - listitem [ref=e110]:
              - link "Contact" [ref=e111] [cursor=pointer]:
                - /url: ../../../Contact.html
            - listitem [ref=e112]:
              - link " The ROS 2 Project" [ref=e113] [cursor=pointer]:
                - /url: ../../../The-ROS2-Project.html
                - button "" [ref=e114]
                - text: The ROS 2 Project
              - text:  
            - listitem [ref=e115]:
              - link "Package Docs" [ref=e116] [cursor=pointer]:
                - /url: ../../../Package-Docs.html
            - listitem [ref=e117]:
              - link " Related Projects" [ref=e118] [cursor=pointer]:
                - /url: ../../../Related-Projects.html
                - button "" [ref=e119]
                - text: Related Projects
            - listitem [ref=e120]:
              - link "Glossary" [ref=e121] [cursor=pointer]:
                - /url: ../../../Glossary.html
            - listitem [ref=e122]:
              - link "Citations" [ref=e123] [cursor=pointer]:
                - /url: ../../../Citations.html
    - generic [ref=e124]:
      - text: 
      - generic [ref=e126]:
        - navigation "Page navigation" [ref=e127]:
          - list [ref=e128]:
            - listitem [ref=e129]:
              - link "Home" [ref=e130] [cursor=pointer]:
                - /url: ../../../index.html
                - text: 
            - listitem [ref=e131]:
              - text: /
              - link "Tutorials" [ref=e132] [cursor=pointer]:
                - /url: ../../../Tutorials.html
            - listitem [ref=e133]:
              - text: /
              - link "Advanced" [ref=e134] [cursor=pointer]:
                - /url: ../../Advanced.html
            - listitem [ref=e135]:
              - text: /
              - link "Security" [ref=e136] [cursor=pointer]:
                - /url: Security-Main.html
            - listitem [ref=e137]: /Setting access controls
            - listitem [ref=e138]:
              - link " Edit on GitHub" [ref=e139] [cursor=pointer]:
                - /url: https://github.com/ros2/ros2_documentation/blob/rolling/source/Tutorials/Advanced/Security/Access-Controls.rst
          - separator [ref=e140]
        - main [ref=e141]:
          - generic [ref=e142]:
            - paragraph [ref=e143]:
              - strong [ref=e144]:
                - text: You're reading the documentation for a development version. For the latest released version, please have a look at
                - link "Lyrical" [ref=e145] [cursor=pointer]:
                  - /url: ../../../../lyrical/Tutorials/Advanced/Security/Access-Controls.html
                - text: .
            - generic [ref=e146]:
              - heading "Setting access controls " [level=1] [ref=e147]:
                - text: Setting access controls
                - link "" [ref=e148] [cursor=pointer]:
                  - /url: "#setting-access-controls"
              - paragraph [ref=e149]:
                - strong [ref=e150]: "Goal:"
                - text: Limit the topics a node can use.
              - paragraph [ref=e151]:
                - strong [ref=e152]: "Tutorial level:"
                - text: Advanced
              - paragraph [ref=e153]:
                - strong [ref=e154]: "Time:"
                - text: 20 minutes
              - navigation [ref=e155]:
                - paragraph [ref=e156]: Contents
                - list [ref=e157]:
                  - listitem [ref=e158]:
                    - paragraph [ref=e159]:
                      - link "Background" [ref=e160] [cursor=pointer]:
                        - /url: "#background"
                    - list [ref=e161]:
                      - listitem [ref=e162]:
                        - paragraph [ref=e163]:
                          - link "Modify permissions.xml" [ref=e164] [cursor=pointer]:
                            - /url: "#modify-permissions-xml"
                            - text: Modify
                            - code [ref=e165]: permissions.xml
                      - listitem [ref=e166]:
                        - paragraph [ref=e167]:
                          - link "Sign the policy file" [ref=e168] [cursor=pointer]:
                            - /url: "#sign-the-policy-file"
                      - listitem [ref=e169]:
                        - paragraph [ref=e170]:
                          - link "Launch the node" [ref=e171] [cursor=pointer]:
                            - /url: "#launch-the-node"
                      - listitem [ref=e172]:
                        - paragraph [ref=e173]:
                          - link "Use the templates" [ref=e174] [cursor=pointer]:
                            - /url: "#use-the-templates"
              - generic [ref=e175]:
                - heading "Background " [level=2] [ref=e176]:
                  - link "Background" [ref=e177] [cursor=pointer]:
                    - /url: "#id1"
                  - link "" [ref=e178] [cursor=pointer]:
                    - /url: "#background"
                - paragraph [ref=e179]:
                  - text: Before proceeding ensure you have completed the
                  - link "Setting up security" [ref=e180] [cursor=pointer]:
                    - /url: Introducing-ros2-security.html
                  - text: tutorial.
                - paragraph [ref=e181]: Permissions are quite flexible and can be used to control many behaviors within the ROS graph.
                - paragraph [ref=e182]:
                  - text: For this tutorial, we demonstrate a policy which only allows publishing messages on the default
                  - code [ref=e183]: chatter
                  - text: topic. This would prevent, for instance, remapping the topic when launching the listener or using the same security enclaves for another purpose.
                - paragraph [ref=e184]:
                  - text: In order to enforce this policy, we need to update the
                  - code [ref=e185]: permissions.xml
                  - text: file and re-sign it before launching the node. This can be done by modifying the permissions file by hand, or by using XML templates.
                - generic [ref=e186]:
                  - heading "Modify permissions.xml " [level=3] [ref=e187]:
                    - link "Modify permissions.xml" [ref=e188] [cursor=pointer]:
                      - /url: "#id2"
                      - text: Modify
                      - code [ref=e189]: permissions.xml
                    - link "" [ref=e190] [cursor=pointer]:
                      - /url: "#modify-permissions-xml"
                  - paragraph [ref=e191]:
                    - text: Begin by making a backup of your permissions files, and open
                    - code [ref=e192]: permissions.xml
                    - text: "for editing:"
                  - generic [ref=e194]:
                    - generic [ref=e195]: $ cd ~/sros2_demo/demo_keystore/enclaves/talker_listener/talker $ mv permissions.p7s permissions.p7s~ $ mv permissions.xml permissions.xml~ $ vi permissions.xml
                    - button "Copy to clipboard" [ref=e196] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e197]
                  - paragraph [ref=e201]:
                    - text: We will be modifying the
                    - code [ref=e202]: <allow_rule>
                    - text: for
                    - code [ref=e203]: <publish>
                    - text: and
                    - code [ref=e204]: <subscribe>
                    - text: . The topics in this XML file use the DDS naming format, not the ROS name. Find details on mapping topic names between ROS and DDS in the
                    - link "Topic and Service Names design document" [ref=e205] [cursor=pointer]:
                      - /url: https://design.ros2.org/articles/topic_and_service_names.html#mapping-of-ros-2-topic-and-service-names-to-dds-concepts
                    - text: .
                  - paragraph [ref=e206]:
                    - text: Paste the following XML content into
                    - code [ref=e207]: permissions.xml
                    - text: ", save the file and exit the text editor. This shows the"
                    - code [ref=e208]: chatter
                    - text: and
                    - code [ref=e209]: rosout
                    - text: ROS topics renamed to the DDS
                    - code [ref=e210]: rt/chatter
                    - text: and
                    - code [ref=e211]: rt/rosout
                    - text: "topics, respectively:"
                  - generic [ref=e213]:
                    - generic [ref=e214]:
                      - text: <dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd"> <permissions> <grant name="/talker_listener/talker"> <subject_name>CN=/talker_listener/talker</subject_name> <validity> <not_before>2021-06-01T16:57:53</not_before> <not_after>2031-05-31T16:57:53</not_after> </validity> <allow_rule> <domains> <id>0</id> </domains> <publish> <topics>
                      - generic [ref=e215]: <topic>rt/chatter</topic>
                      - generic [ref=e216]: <topic>rt/rosout</topic>
                      - generic [ref=e217]: <topic>rt/parameter_events</topic>
                      - generic [ref=e218]: <topic>*/talker/*</topic>
                      - text: </topics> </publish> <subscribe> <topics>
                      - generic [ref=e219]: <topic>rt/parameter_events</topic>
                      - generic [ref=e220]: <topic>*/talker/*</topic>
                      - text: </topics> </subscribe> </allow_rule> <allow_rule> <domains> <id>0</id> </domains> <publish> <topics> <topic>ros_discovery_info</topic> </topics> </publish> <subscribe> <topics> <topic>ros_discovery_info</topic> </topics> </subscribe> </allow_rule> <default>DENY</default> </grant> </permissions> </dds>
                    - button "Copy to clipboard" [ref=e221] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e222]
                  - paragraph [ref=e226]:
                    - text: This policy allows the talker to publish on the
                    - code [ref=e227]: chatter
                    - text: and the
                    - code [ref=e228]: rosout
                    - text: topics. It also includes publish and subscribe permissions needed for the talker node to manage parameters (a requirement for all nodes). Discovery permissions remain unchanged from the original template.
                - generic [ref=e229]:
                  - heading "Sign the policy file " [level=3] [ref=e230]:
                    - link "Sign the policy file" [ref=e231] [cursor=pointer]:
                      - /url: "#id3"
                    - link "" [ref=e232] [cursor=pointer]:
                      - /url: "#sign-the-policy-file"
                  - paragraph [ref=e233]:
                    - text: This next command creates the new S/MIME signed policy file
                    - code [ref=e234]: permissions.p7s
                    - text: from the updated XML file
                    - code [ref=e235]: permissions.xml
                    - text: . The file must be signed with the Permissions CA certificate,
                    - strong [ref=e236]: which requires access to the Permissions CA private key
                    - text: . If the private key has been protected, additional steps may be required to unlock and use it according to your security plan.
                  - generic [ref=e238]:
                    - generic [ref=e239]: $ openssl smime -sign -text -in permissions.xml -out permissions.p7s \ --signer permissions_ca.cert.pem \ -inkey ~/sros2_demo/demo_keystore/private/permissions_ca.key.pem
                    - button "Copy to clipboard" [ref=e240] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e241]
                - generic [ref=e245]:
                  - heading "Launch the node " [level=3] [ref=e246]:
                    - link "Launch the node" [ref=e247] [cursor=pointer]:
                      - /url: "#id4"
                    - link "" [ref=e248] [cursor=pointer]:
                      - /url: "#launch-the-node"
                  - paragraph [ref=e249]: "With the updated permissions in place, we can launch the node successfully using the same command used in prior tutorials:"
                  - generic [ref=e251]:
                    - generic [ref=e252]: $ ros2 run demo_nodes_cpp talker --ros-args --enclave /talker_listener/talker
                    - button "Copy to clipboard" [ref=e253] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e254]
                  - paragraph [ref=e258]:
                    - text: However, attempting to remap the
                    - code [ref=e259]: chatter
                    - text: topic prevents the node from launching (note that this requires the
                    - code [ref=e260]: ROS_SECURITY_STRATEGY
                    - text: set to
                    - code [ref=e261]: Enforce
                    - text: ).
                  - generic [ref=e263]:
                    - generic [ref=e264]: $ ros2 run demo_nodes_cpp talker --ros-args --enclave /talker_listener/talker \ --remap chatter:=not_chatter
                    - button "Copy to clipboard" [ref=e265] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e266]
                - generic [ref=e270]:
                  - heading "Use the templates " [level=3] [ref=e271]:
                    - link "Use the templates" [ref=e272] [cursor=pointer]:
                      - /url: "#id5"
                    - link "" [ref=e273] [cursor=pointer]:
                      - /url: "#use-the-templates"
                  - paragraph [ref=e274]:
                    - text: Security policies can quickly become confusing, so the
                    - code [ref=e275]: sros2
                    - text: utilities add the ability to create policies from templates. Do this by using the
                    - link "sample policy file" [ref=e276] [cursor=pointer]:
                      - /url: https://github.com/ros2/sros2/blob/rolling/sros2/test/policies/sample.policy.xml#L1
                    - text: provided in the
                    - code [ref=e277]: sros2
                    - text: repository. Let’s create a policy for both the
                    - code [ref=e278]: talker
                    - text: and the
                    - code [ref=e279]: listener
                    - text: to only use the
                    - code [ref=e280]: chatter
                    - text: topic.
                  - paragraph [ref=e281]:
                    - text: Begin by downloading the
                    - code [ref=e282]: sros2
                    - text: "repository with the sample policy files:"
                  - generic [ref=e284]:
                    - generic [ref=e285]: $ git clone https://github.com/ros2/sros2.git /tmp/sros2
                    - button "Copy to clipboard" [ref=e286] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e287]
                  - paragraph [ref=e291]:
                    - text: Then use the
                    - code [ref=e292]: create_permission
                    - text: "verb while pointing to the sample policy to generate the XML permission files:"
                  - generic [ref=e294]:
                    - generic [ref=e295]: $ ros2 security create_permission demo_keystore \ /talker_listener/talker \ /tmp/sros2/sros2/test/policies/sample.policy.xml $ ros2 security create_permission demo_keystore \ /talker_listener/listener \ /tmp/sros2/sros2/test/policies/sample.policy.xml
                    - button "Copy to clipboard" [ref=e296] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e297]
                  - paragraph [ref=e301]:
                    - text: These permission files allow nodes to only publish or subscribe to the
                    - code [ref=e302]: chatter
                    - text: topic, and enable communications required for parameters.
                  - paragraph [ref=e303]:
                    - text: In one terminal with security enabled as in previous security tutorials, run the
                    - code [ref=e304]: talker
                    - text: "demo program:"
                  - generic [ref=e306]:
                    - generic [ref=e307]: $ ros2 run demo_nodes_cpp talker --ros-args -e /talker_listener/talker
                    - button "Copy to clipboard" [ref=e308] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e309]
                  - paragraph [ref=e313]:
                    - text: In another terminal do the same with the
                    - code [ref=e314]: listener
                    - text: "program:"
                  - generic [ref=e316]:
                    - generic [ref=e317]: $ ros2 run demo_nodes_py listener --ros-args -e /talker_listener/listener
                    - button "Copy to clipboard" [ref=e318] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e319]
                  - paragraph [ref=e323]:
                    - text: At this point, your
                    - code [ref=e324]: talker
                    - text: and
                    - code [ref=e325]: listener
                    - text: nodes will be communicating securely using explicit access control lists. However, the following attempt for the
                    - code [ref=e326]: listener
                    - text: node to subscribe to a topic other than
                    - code [ref=e327]: chatter
                    - text: "will fail:"
                  - generic [ref=e329]:
                    - generic [ref=e330]: $ ros2 run demo_nodes_py listener --ros-args --enclave /talker_listener/listener \ --remap chatter:=not_chatter
                    - button "Copy to clipboard" [ref=e331] [cursor=pointer]:
                      - img "Copy to clipboard" [ref=e332]
        - generic [ref=e336]:
          - navigation "Footer" [ref=e337]:
            - link "Previous" [ref=e338] [cursor=pointer]:
              - /url: Examine-Traffic.html
              - generic [ref=e339]: 
              - text: Previous
            - link "Next" [ref=e340] [cursor=pointer]:
              - /url: Deployment-Guidelines.html
              - text: Next
              - generic [ref=e341]: 
          - separator [ref=e342]
          - contentinfo [ref=e343]:
            - paragraph [ref=e344]: © Copyright 2026, Open Robotics.
          - text: Built with
          - link "Sphinx" [ref=e345] [cursor=pointer]:
            - /url: https://www.sphinx-doc.org/
          - text: using a
          - link "theme" [ref=e346] [cursor=pointer]:
            - /url: https://github.com/readthedocs/sphinx_rtd_theme
          - text: provided by
          - link "Read the Docs" [ref=e347] [cursor=pointer]:
            - /url: https://readthedocs.org
          - text: .
  - note "versions" [ref=e348]:
    - generic [ref=e349] [cursor=pointer]:
      - generic [ref=e350]:  Other Versions
      - text: "v: rolling"
      - generic [ref=e351]: 