#!/usr/bin/env python3
"""Generate (or drift-check) the third-party dependency notices.

Scope: **direct** dependencies of the workspace crates (Rust, with licenses from
``cargo metadata``) and the project's declared Python dependencies (with locked
versions from ``uv.lock``). Direct deps are deterministic and stable — they only
change when a ``Cargo.toml`` / ``pyproject.toml`` is edited — so the ``--check``
mode does not churn on transitive version bumps. A full transitive bill of
materials is a release-time step with dedicated tooling (``cargo about`` /
``cargo deny`` / ``pip-licenses``); see the release checklist in
``THIRD_PARTY_NOTICES.md``.

Usage::

    python scripts/generate_third_party_notices.py --write   # regenerate the file
    python scripts/generate_third_party_notices.py --check   # exit 1 on drift (CI)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "THIRD_PARTY_NOTICES.generated.md"
HEADER = "<!-- generated by scripts/generate_third_party_notices.py; do not edit by hand -->"


def _cargo_metadata() -> dict:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(out.stdout)


def rust_direct_dependencies() -> list[tuple[str, str, str]]:
    """Return sorted ``(name, version, license)`` for direct deps of our crates."""
    meta = _cargo_metadata()
    by_id = {p["id"]: p for p in meta["packages"]}
    workspace_ids = set(meta["workspace_members"])
    workspace_names = {by_id[i]["name"] for i in workspace_ids if i in by_id}

    direct_ids: set[str] = set()
    for node in meta["resolve"]["nodes"]:
        if node["id"] not in workspace_ids:
            continue
        for dep in node["deps"]:
            direct_ids.add(dep["pkg"])

    rows: set[tuple[str, str, str]] = set()
    for dep_id in direct_ids:
        pkg = by_id.get(dep_id)
        if pkg is None or pkg["name"] in workspace_names:
            continue
        license_ = pkg.get("license") or pkg.get("license_file") or "UNKNOWN"
        rows.add((pkg["name"], pkg["version"], license_))
    return sorted(rows)


def _names_from_dep_specs(specs: list[str]) -> set[str]:
    names = set()
    for spec in specs:
        # Strip version/extra markers: "numpy>=1.26", "ruff>=0.6", "pkg[extra]".
        name = spec.split(";")[0].strip()
        for sep in ("==", ">=", "<=", "~=", ">", "<", "!=", "["):
            name = name.split(sep)[0]
        name = name.strip()
        if name:
            names.add(name.lower().replace("_", "-"))
    return names


def python_direct_dependencies() -> list[tuple[str, str]]:
    """Return sorted ``(name, locked_version)`` for declared Python deps."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
    declared: set[str] = set()
    declared |= _names_from_dep_specs(pyproject.get("project", {}).get("dependencies", []))
    for group in pyproject.get("dependency-groups", {}).values():
        declared |= _names_from_dep_specs(group)

    locked: dict[str, str] = {}
    lock_path = REPO_ROOT / "uv.lock"
    if lock_path.exists():
        lock = tomllib.loads(lock_path.read_text())
        for pkg in lock.get("package", []):
            locked[pkg["name"].lower().replace("_", "-")] = pkg.get("version", "?")

    rows = [(name, locked.get(name, "(unlocked)")) for name in declared]
    return sorted(rows)


def render() -> str:
    rust = rust_direct_dependencies()
    python = python_direct_dependencies()
    lines = [
        HEADER,
        "",
        "# Third-Party Notices (generated)",
        "",
        "Direct dependencies of the workspace crates and declared Python packages.",
        "Regenerate with `python scripts/generate_third_party_notices.py --write`.",
        "See `THIRD_PARTY_NOTICES.md` for the curated overview and release checklist.",
        "",
        "## Rust direct dependencies",
        "",
        "| Crate | Version | License |",
        "|---|---|---|",
    ]
    lines += [f"| `{name}` | {version} | {license_} |" for name, version, license_ in rust]
    lines += [
        "",
        "## Python declared dependencies (versions locked in `uv.lock`)",
        "",
        "Licenses are not recorded in `uv.lock`; resolve them with `pip-licenses` or",
        "from each project's PyPI page at release time.",
        "",
        "| Package | Locked version |",
        "|---|---|",
    ]
    lines += [f"| `{name}` | {version} |" for name, version in python]
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write the generated notices file")
    group.add_argument("--check", action="store_true", help="exit nonzero if the file is stale")
    args = parser.parse_args(argv)

    content = render()
    if args.write:
        OUTPUT.write_text(content)
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
        return 0

    if not OUTPUT.exists():
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is missing; run with --write", file=sys.stderr)
        return 1
    current = OUTPUT.read_text()
    if current != content:
        print(
            f"{OUTPUT.relative_to(REPO_ROOT)} is out of date; "
            "run `python scripts/generate_third_party_notices.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
