#!/usr/bin/env python3
"""Generate (or drift-check) the third-party dependency notices.

Scope: **direct** dependencies of the workspace crates (Rust, with licenses from
``cargo metadata``) and the project's declared Python dependencies (with locked
versions from ``uv.lock``). Direct deps are deterministic and stable — they only
change when a ``Cargo.toml`` / ``pyproject.toml`` is edited — so the ``--check``
mode does not churn on transitive version bumps. A full transitive bill of
materials is a release-time step with dedicated tooling (``cargo about`` /
``cargo deny`` / ``pip-licenses``); see the release checklist in
``THIRD_PARTY_NOTICES.md``.

Usage::

    python scripts/generate_third_party_notices.py --write   # regenerate the file
    python scripts/generate_third_party_notices.py --check   # exit 1 on drift (CI)
"""

from __future__ import annotations

import argparse
import json
import os
import selectors
import signal
import stat
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "THIRD_PARTY_NOTICES.generated.md"
HEADER = (
    "<!-- generated by scripts/generate_third_party_notices.py; do not edit by hand -->"
)
MAX_INPUT_BYTES = 16 * 1024 * 1024
MAX_METADATA_BYTES = 32 * 1024 * 1024
MAX_OUTPUT_BYTES = 4 * 1024 * 1024
SUBPROCESS_TIMEOUT_SECONDS = 120.0


class NoticeGenerationError(RuntimeError):
    """A bounded input or subprocess violated the notice-generation contract."""


def _read_regular_bytes(path: Path, *, max_bytes: int, label: str) -> bytes:
    try:
        before = path.lstat()
    except OSError as error:
        raise NoticeGenerationError(
            f"cannot inspect {label} {path}: {error}"
        ) from error
    if not stat.S_ISREG(before.st_mode):
        raise NoticeGenerationError(
            f"{label} must be a regular, non-symlink file: {path}"
        )
    if before.st_size > max_bytes:
        raise NoticeGenerationError(
            f"{label} exceeds the {max_bytes}-byte limit: {path}"
        )

    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise NoticeGenerationError(f"cannot open {label} {path}: {error}") from error
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode) or (opened.st_dev, opened.st_ino) != (
            before.st_dev,
            before.st_ino,
        ):
            raise NoticeGenerationError(f"{label} changed while opening: {path}")
        chunks: list[bytes] = []
        remaining = max_bytes + 1
        while remaining:
            chunk = os.read(descriptor, min(65_536, remaining))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        after = os.fstat(descriptor)
    finally:
        os.close(descriptor)
    payload = b"".join(chunks)
    if len(payload) > max_bytes:
        raise NoticeGenerationError(
            f"{label} exceeds the {max_bytes}-byte limit: {path}"
        )
    if (opened.st_dev, opened.st_ino, opened.st_size, opened.st_mtime_ns) != (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    ) or len(payload) != after.st_size:
        raise NoticeGenerationError(f"{label} changed while reading: {path}")
    return payload


def _read_regular_text(path: Path, *, max_bytes: int, label: str) -> str:
    try:
        return _read_regular_bytes(path, max_bytes=max_bytes, label=label).decode(
            "utf-8"
        )
    except UnicodeDecodeError as error:
        raise NoticeGenerationError(f"{label} is not valid UTF-8: {path}") from error


def _terminate(process: subprocess.Popen[bytes]) -> None:
    if process.returncode is not None:
        return
    if os.name == "posix":
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        except PermissionError:
            if sys.platform != "darwin":
                raise
    else:
        try:
            process.kill()
        except OSError:
            pass


def _run_bounded(
    command: list[str],
    *,
    cwd: Path,
    timeout_seconds: float = SUBPROCESS_TIMEOUT_SECONDS,
    max_output_bytes: int = MAX_METADATA_BYTES,
) -> subprocess.CompletedProcess[str]:
    """Run a command with one aggregate stdout/stderr byte and wall-time budget."""

    if timeout_seconds <= 0:
        raise subprocess.TimeoutExpired(command, timeout_seconds)
    if max_output_bytes < 0:
        raise NoticeGenerationError(
            f"invalid negative aggregate subprocess output budget: {max_output_bytes}"
        )
    process = subprocess.Popen(
        command,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        start_new_session=os.name == "posix",
    )
    stdout_stream = process.stdout
    stderr_stream = process.stderr
    selector: selectors.BaseSelector | None = None
    buffers = {"stdout": bytearray(), "stderr": bytearray()}
    total = 0
    deadline = time.monotonic() + timeout_seconds
    try:
        if stdout_stream is None or stderr_stream is None:
            raise NoticeGenerationError("subprocess pipes were not created")
        selector = selectors.DefaultSelector()
        selector.register(stdout_stream, selectors.EVENT_READ, "stdout")
        selector.register(stderr_stream, selectors.EVENT_READ, "stderr")
        while selector.get_map():
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise subprocess.TimeoutExpired(command, timeout_seconds)
            for key, _events in selector.select(min(remaining, 0.25)):
                chunk = os.read(key.fd, min(65_536, max_output_bytes - total + 1))
                if not chunk:
                    selector.unregister(key.fileobj)
                    key.fileobj.close()
                    continue
                total += len(chunk)
                if total > max_output_bytes:
                    raise NoticeGenerationError(
                        "subprocess output exceeds the aggregate "
                        f"{max_output_bytes}-byte limit"
                    )
                buffers[key.data].extend(chunk)
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise subprocess.TimeoutExpired(command, timeout_seconds)
        if os.name == "posix":
            _terminate(process)
        return_code = process.wait(timeout=remaining)
    except BaseException:
        _terminate(process)
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            pass
        raise
    finally:
        _terminate(process)
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            pass
        if selector is not None:
            selector.close()
        for stream in (stdout_stream, stderr_stream):
            if stream is not None and not stream.closed:
                stream.close()

    try:
        stdout = bytes(buffers["stdout"]).decode("utf-8")
        stderr = bytes(buffers["stderr"]).decode("utf-8")
    except UnicodeDecodeError as error:
        raise NoticeGenerationError("subprocess output is not valid UTF-8") from error
    result = subprocess.CompletedProcess(command, return_code, stdout, stderr)
    if return_code != 0:
        raise subprocess.CalledProcessError(
            return_code, command, output=stdout, stderr=stderr
        )
    return result


def _json_object(payload: str, *, label: str) -> dict[str, Any]:
    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise NoticeGenerationError(f"{label} has duplicate key {key!r}")
            result[key] = value
        return result

    def reject_constant(value: str) -> Any:
        raise NoticeGenerationError(f"{label} has invalid JSON constant {value}")

    try:
        value = json.loads(
            payload,
            object_pairs_hook=reject_duplicates,
            parse_constant=reject_constant,
        )
    except (ValueError, RecursionError) as error:
        raise NoticeGenerationError(f"cannot parse {label}: {error}") from error
    if not isinstance(value, dict):
        raise NoticeGenerationError(f"{label} must be a JSON object")
    return value


def _toml_object(path: Path, *, label: str) -> dict[str, Any]:
    payload = _read_regular_text(path, max_bytes=MAX_INPUT_BYTES, label=label)
    try:
        value = tomllib.loads(payload)
    except (tomllib.TOMLDecodeError, RecursionError) as error:
        raise NoticeGenerationError(f"cannot parse {label}: {error}") from error
    if not isinstance(value, dict):
        raise NoticeGenerationError(f"{label} must be a TOML table")
    return value


def _cargo_metadata() -> dict:
    out = _run_bounded(
        ["cargo", "metadata", "--locked", "--all-features", "--format-version", "1"],
        cwd=REPO_ROOT,
    )
    metadata = _json_object(out.stdout, label="cargo metadata")
    packages = metadata.get("packages")
    members = metadata.get("workspace_members")
    resolve = metadata.get("resolve")
    if (
        not isinstance(packages, list)
        or not isinstance(members, list)
        or not all(isinstance(member, str) for member in members)
        or not isinstance(resolve, dict)
        or not isinstance(resolve.get("nodes"), list)
    ):
        raise NoticeGenerationError("cargo metadata has an invalid top-level schema")
    return metadata


def rust_direct_dependencies() -> list[tuple[str, str, str]]:
    """Return sorted ``(name, version, license)`` for direct deps of our crates."""
    meta = _cargo_metadata()
    by_id: dict[str, dict[str, Any]] = {}
    for index, package in enumerate(meta["packages"]):
        if not isinstance(package, dict):
            raise NoticeGenerationError(
                f"cargo metadata packages[{index}] must be an object"
            )
        package_id = package.get("id")
        for field in ("name", "version"):
            if not isinstance(package.get(field), str) or not package[field]:
                raise NoticeGenerationError(
                    f"cargo metadata packages[{index}].{field} must be a string"
                )
        if not isinstance(package_id, str) or not package_id or package_id in by_id:
            raise NoticeGenerationError(
                f"cargo metadata packages[{index}].id is invalid or duplicated"
            )
        for field in ("license", "license_file"):
            if package.get(field) is not None and not isinstance(package[field], str):
                raise NoticeGenerationError(
                    f"cargo metadata packages[{index}].{field} must be null or a string"
                )
        by_id[package_id] = package
    workspace_ids = set(meta["workspace_members"])
    if len(workspace_ids) != len(
        meta["workspace_members"]
    ) or not workspace_ids.issubset(by_id):
        raise NoticeGenerationError(
            "cargo metadata workspace_members are duplicated or unresolved"
        )
    workspace_names = {by_id[i]["name"] for i in workspace_ids}

    direct_ids: set[str] = set()
    for index, node in enumerate(meta["resolve"]["nodes"]):
        if not isinstance(node, dict) or not isinstance(node.get("id"), str):
            raise NoticeGenerationError(
                f"cargo metadata resolve.nodes[{index}] has an invalid schema"
            )
        deps = node.get("deps")
        if not isinstance(deps, list):
            raise NoticeGenerationError(
                f"cargo metadata resolve.nodes[{index}].deps must be a list"
            )
        if node["id"] not in workspace_ids:
            continue
        for dep_index, dep in enumerate(deps):
            if not isinstance(dep, dict) or not isinstance(dep.get("pkg"), str):
                raise NoticeGenerationError(
                    "cargo metadata resolve.nodes"
                    f"[{index}].deps[{dep_index}] has an invalid schema"
                )
            if dep["pkg"] not in by_id:
                raise NoticeGenerationError(
                    "cargo metadata resolve dependency refers to an unknown package"
                )
            direct_ids.add(dep["pkg"])

    rows: set[tuple[str, str, str]] = set()
    for dep_id in direct_ids:
        pkg = by_id.get(dep_id)
        if pkg is None or pkg["name"] in workspace_names:
            continue
        license_ = pkg.get("license") or pkg.get("license_file") or "UNKNOWN"
        rows.add((pkg["name"], pkg["version"], license_))
    return sorted(rows)


def _names_from_dep_specs(specs: list[str]) -> set[str]:
    names = set()
    for spec in specs:
        # Strip version/extra markers: "numpy>=1.26", "ruff>=0.6", "pkg[extra]".
        name = spec.split(";")[0].strip()
        for sep in ("==", ">=", "<=", "~=", ">", "<", "!=", "["):
            name = name.split(sep)[0]
        name = name.strip()
        if name:
            names.add(name.lower().replace("_", "-"))
    return names


def python_direct_dependencies() -> list[tuple[str, str]]:
    """Return declared Python deps with every marker-qualified locked version."""
    pyproject = _toml_object(REPO_ROOT / "pyproject.toml", label="pyproject.toml")
    project = pyproject.get("project", {})
    groups = pyproject.get("dependency-groups", {})
    if not isinstance(project, dict) or not isinstance(groups, dict):
        raise NoticeGenerationError(
            "pyproject dependency tables have an invalid schema"
        )
    project_dependencies = project.get("dependencies", [])
    if not isinstance(project_dependencies, list) or not all(
        isinstance(spec, str) for spec in project_dependencies
    ):
        raise NoticeGenerationError("project.dependencies must be a string list")
    for name, specs in groups.items():
        if (
            not isinstance(name, str)
            or not isinstance(specs, list)
            or not all(isinstance(spec, str) for spec in specs)
        ):
            raise NoticeGenerationError(
                "dependency-groups must map names to string lists"
            )
    declared: set[str] = set()
    declared |= _names_from_dep_specs(project_dependencies)
    for group in groups.values():
        declared |= _names_from_dep_specs(group)

    locked: dict[str, set[str]] = {}
    lock_path = REPO_ROOT / "uv.lock"
    if lock_path.exists() or lock_path.is_symlink():
        lock = _toml_object(lock_path, label="uv.lock")
        packages = lock.get("package", [])
        if not isinstance(packages, list):
            raise NoticeGenerationError("uv.lock package must be a list")
        for index, pkg in enumerate(packages):
            if not isinstance(pkg, dict) or not isinstance(pkg.get("name"), str):
                raise NoticeGenerationError(
                    f"uv.lock package[{index}] has an invalid schema"
                )
            version = pkg.get("version", "?")
            if not isinstance(version, str):
                raise NoticeGenerationError(
                    f"uv.lock package[{index}].version must be a string"
                )
            name = pkg["name"].lower().replace("_", "-")
            markers = pkg.get("resolution-markers", [])
            if isinstance(markers, str):
                markers = [markers]
            if not isinstance(markers, list) or not all(
                isinstance(marker, str) for marker in markers
            ):
                raise NoticeGenerationError(
                    f"uv.lock package[{index}].resolution-markers is invalid"
                )
            marker_suffix = f" [{'; '.join(markers)}]" if markers else ""
            locked.setdefault(name, set()).add(f"{version}{marker_suffix}")

    rows = [
        (name, "; ".join(sorted(locked[name])) if name in locked else "(unlocked)")
        for name in declared
    ]
    return sorted(rows)


def render() -> str:
    rust = rust_direct_dependencies()
    python = python_direct_dependencies()
    lines = [
        HEADER,
        "",
        "# Third-Party Notices (generated)",
        "",
        "Direct dependencies of the workspace crates and declared Python packages.",
        "Regenerate with `python scripts/generate_third_party_notices.py --write`.",
        "See `THIRD_PARTY_NOTICES.md` for the curated overview and release checklist.",
        "",
        "## Rust direct dependencies",
        "",
        "| Crate | Version | License |",
        "|---|---|---|",
    ]
    lines += [
        f"| `{name}` | {version} | {license_} |" for name, version, license_ in rust
    ]
    lines += [
        "",
        "## Python declared dependencies (versions locked in `uv.lock`)",
        "",
        "Licenses are not recorded in `uv.lock`; resolve them with `pip-licenses` or",
        "from each project's PyPI page at release time.",
        "",
        "| Package | Locked version |",
        "|---|---|",
    ]
    lines += [f"| `{name}` | {version} |" for name, version in python]
    lines.append("")
    return "\n".join(lines)


def _atomic_write(path: Path, content: str) -> None:
    payload = content.encode("utf-8")
    if len(payload) > MAX_OUTPUT_BYTES:
        raise NoticeGenerationError(
            f"generated output exceeds the {MAX_OUTPUT_BYTES}-byte limit"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.parent.is_symlink() or not path.parent.is_dir():
        raise NoticeGenerationError(
            f"output parent must be a real directory: {path.parent}"
        )
    if path.exists() or path.is_symlink():
        try:
            mode = path.lstat().st_mode
        except OSError as error:
            raise NoticeGenerationError(
                f"cannot inspect output {path}: {error}"
            ) from error
        if not stat.S_ISREG(mode):
            raise NoticeGenerationError(
                f"output must be a regular, non-symlink file: {path}"
            )

    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--write", action="store_true", help="write the generated notices file"
    )
    group.add_argument(
        "--check", action="store_true", help="exit nonzero if the file is stale"
    )
    args = parser.parse_args(argv)

    try:
        content = render()
    except (
        NoticeGenerationError,
        OSError,
        subprocess.SubprocessError,
    ) as error:
        print(f"cannot generate notices: {error}", file=sys.stderr)
        return 1
    if args.write:
        try:
            _atomic_write(OUTPUT, content)
        except (NoticeGenerationError, OSError) as error:
            print(f"cannot write notices: {error}", file=sys.stderr)
            return 1
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
        return 0

    if not OUTPUT.exists() and not OUTPUT.is_symlink():
        print(
            f"{OUTPUT.relative_to(REPO_ROOT)} is missing; run with --write",
            file=sys.stderr,
        )
        return 1
    try:
        current = _read_regular_text(
            OUTPUT, max_bytes=MAX_OUTPUT_BYTES, label="generated notices"
        )
    except NoticeGenerationError as error:
        print(str(error), file=sys.stderr)
        return 1
    if current != content:
        print(
            f"{OUTPUT.relative_to(REPO_ROOT)} is out of date; "
            "run `python scripts/generate_third_party_notices.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
